### ISSUE TITLE
Error on npm start: details.family.toLowerCase is not a function

### ISSUE THREAD

**Issue by laedit** [jellyfin/jellyfin-vue#1864]
### Description of the bug

Hi, 
I wanted to take a look at this promising project but encounter an error when following the Getting Started part of the readme:
```
 FATAL  details.family.toLowerCase is not a function                                                          10:52:23

  at C:\Users\jerem\Downloads\jellyfin-vue\node_modules\ip\lib\ip.js:385:39
  at Array.filter (<anonymous>)
  at C:\Users\jerem\Downloads\jellyfin-vue\node_modules\ip\lib\ip.js:384:37
  at Array.map (<anonymous>)
  at ip.address (C:\Users\jerem\Downloads\jellyfin-vue\node_modules\ip\lib\ip.js:379:37)
  at Listener.computeURL (C:\Users\jerem\Downloads\jellyfin-vue\node_modules\@nuxt\server\dist\server.js:469:60)
  at Listener.listen (C:\Users\jerem\Downloads\jellyfin-vue\node_modules\@nuxt\server\dist\server.js:510:10)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Server.listen (C:\Users\jerem\Downloads\jellyfin-vue\node_modules\@nuxt\server\dist\server.js:973:5)
  at async Object._listenDev (C:\Users\jerem\Downloads\jellyfin-vue\node_modules\@nuxt\cli\dist\cli-dev.js:86:5)
```
Did I miss something?

### Steps to reproduce

Follow the getting started part of the readme:
- ` git clone https://github.com/jellyfin/jellyfin-vue.git`
- `cd .\jellyfin-vue\` 
- `npm install` (lots of vulnerabilities marked by npm by the way)
- `npm start` 

### Expected behavior

No error and the server is up and the application ready to be admired.

### Platform

Windows

### Browser

Firefox

### Jellyfin server version

10.8.9

**Comment by ferferga** [comment]
First of all, welcome here! 👋

Yes, it could be said that current master is in maintenance, so if you want to start contributing, please head over to the vite branch where we are working in upgrading this client to Vue 3 (which does have a single warning in npm i, but we're ignoring it for now because we want to update all the dependencies as soon as it reaches master and not in-between, in order to not pollute the commit history).

If you want to stick to current master, Windows is building fine, as you can check in our CI though. First thing I'd try is to check Node version is between the bounds we mention in Readme.
